### PR TITLE
multiple action choosing bug fixed

### PR DESCRIPTION
**Pull request by romanusyk**
Hi! I've found a bug when choosing multiple action. You should compare value array with maximum element, not with index.

### CODE REVIEW

**Comment by garretthoffman** [comment]
I believe this still has a small bug when conditioning on the `len(check) == 0`. I think this should be `len(check) == 1` since `check` will contain the unique index of the argmax.

**Comment by romanusyk** [comment]
You still don't understand that you compare incomparable things there `q == action`, so `check` will contain not the unique index of the argmax, but trash.

**Comment by garretthoffman** [comment]
I am not the author of this library. I agree that incomparable things are being compared and agree with your your change, but I believe it still has a bug that I mentioned above once it is fixed.

Once it is fixed with your suggested change of `check = np.where(agent.value_estimates == agent.value_estimates[action])[0]`, `check` will be an array containing the unique argmax in the case that there is a single maximum. Once it is fixed there will be no case where `len(check) == 0`.

**Comment by romanusyk** [comment]
Yes, of course, you're right. I am sorry not to find it out at once :)

**Comment by bgalbraith** [comment]
this is correct! sorry for the delay in getting it pulled in.

**Pull request merged**
